import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Save, ShieldCheck, UserPlus } from 'lucide-react'
import { useState } from 'react'
import { adminService } from '../services/adminService'
import { AdminError, AdminLoading, AdminPageHeader } from '../components/AdminUi'

export function AdminSettingsPage() {
  const client = useQueryClient()
  const query = useQuery({ queryKey: ['admin', 'settings'], queryFn: adminService.getSettings })
  const [draft, setDraft] = useState<Partial<{ platformFeePercent: number; minWithdrawAmount: number; terms: string }>>({})
  const [fullName, setFullName] = useState(''); const [email, setEmail] = useState(''); const [temporaryPassword, setTemporaryPassword] = useState('')
  const platformFeePercent = draft.platformFeePercent ?? query.data?.platformFeePercent ?? 0
  const minWithdrawAmount = draft.minWithdrawAmount ?? query.data?.minWithdrawAmount ?? 0
  const terms = draft.terms ?? query.data?.terms ?? ''
  const save = useMutation({ mutationFn: () => adminService.updateSettings({ platformFeePercent, minWithdrawAmount, terms }), onSuccess: () => { setDraft({}); client.invalidateQueries({ queryKey: ['admin', 'settings'] }) } })
  const invite = useMutation({ mutationFn: () => adminService.createAdmin({ fullName, email }), onSuccess: (data) => { setTemporaryPassword(data.temporaryPassword); setFullName(''); setEmail('') } })
  if (query.isLoading) return <div className="p-8"><AdminLoading /></div>
  if (query.error) return <div className="p-8"><AdminError /></div>
  return <div className="space-y-6 p-4 sm:p-6 lg:p-8"><AdminPageHeader title="Cấu hình hệ thống" description="Quản lý chính sách nền tảng và tài khoản quản trị." /><div className="grid gap-6 xl:grid-cols-2"><section className="rounded-2xl border bg-white p-6"><div className="flex items-center gap-3"><Save className="text-blue-600" /><h2 className="font-bold">Phí nền tảng</h2></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold">Phí nền tảng (%)<input type="number" min={0} max={100} value={platformFeePercent} onChange={(e) => setDraft((value) => ({ ...value, platformFeePercent: Number(e.target.value) }))} className="profile-input mt-2" /></label><label className="text-sm font-semibold">Rút tối thiểu (VNĐ)<input type="number" min={0} value={minWithdrawAmount} onChange={(e) => setDraft((value) => ({ ...value, minWithdrawAmount: Number(e.target.value) }))} className="profile-input mt-2" /></label></div></section><section className="rounded-2xl border bg-white p-6"><div className="flex items-center gap-3"><ShieldCheck className="text-purple-600" /><h2 className="font-bold">Điều khoản dịch vụ</h2></div><textarea rows={6} value={terms} onChange={(e) => setDraft((value) => ({ ...value, terms: e.target.value }))} className="profile-input mt-6 resize-none" /></section><div className="flex items-center justify-end gap-3 xl:col-span-2">{save.isSuccess && <span className="text-sm font-bold text-green-600">Đã lưu cấu hình.</span>}<button disabled={save.isPending} onClick={() => save.mutate()} className="rounded-xl bg-blue-600 px-6 py-3 text-sm font-bold text-white">Lưu thay đổi</button></div><section className="rounded-2xl border bg-white p-6 xl:col-span-2"><div className="flex items-center gap-3"><UserPlus className="text-green-600" /><h2 className="font-bold">Thêm quản trị viên</h2></div><div className="mt-6 grid gap-5 md:grid-cols-2"><label className="text-sm font-semibold">Họ và tên<input value={fullName} onChange={(e) => setFullName(e.target.value)} className="profile-input mt-2" /></label><label className="text-sm font-semibold">Email<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="profile-input mt-2" /></label></div><div className="mt-5 flex items-center gap-4"><button disabled={!fullName || !email || invite.isPending} onClick={() => invite.mutate()} className="rounded-xl bg-slate-900 px-5 py-2.5 text-sm font-bold text-white disabled:opacity-50">Tạo tài khoản</button>{temporaryPassword && <p className="rounded-lg bg-amber-50 px-4 py-2 text-sm text-amber-800">Mật khẩu tạm thời: <strong>{temporaryPassword}</strong></p>}{invite.error && <p className="text-sm text-red-600">{invite.error.message}</p>}</div></section></div></div>
}
