import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Eye, EyeOff, MessageSquareText, Star, Trash2 } from 'lucide-react'
import { useState } from 'react'
import { adminService } from '../services/adminService'
import { AdminBadge, AdminError, AdminLoading, AdminPageHeader, AdminPagination, AdminStatCard } from '../components/AdminUi'
export function AdminReviewsPage() {
  const [page, setPage] = useState(1); const client = useQueryClient()
  const query = useQuery({ queryKey: ['admin', 'feedbacks', page], queryFn: () => adminService.getFeedbacks({ page, limit: 10 }) })
  const toggle = useMutation({ mutationFn: ({ id, status }: { id: string; status: 'VISIBLE' | 'HIDDEN' }) => adminService.updateFeedbackStatus(id, status), onSuccess: () => client.invalidateQueries({ queryKey: ['admin', 'feedbacks'] }) })
  return <div className="space-y-6 p-4 sm:p-6 lg:p-8"><AdminPageHeader title="Quản lý đánh giá" description="Kiểm duyệt phản hồi của khách hàng." /><section className="grid gap-4 sm:grid-cols-3"><AdminStatCard label="Tổng đánh giá" value={String(query.data?.summary.ratings ?? 0)} icon={MessageSquareText} /><AdminStatCard label="Điểm trung bình" value={(query.data?.summary.average ?? 0).toFixed(2)} icon={Star} tone="amber" /><AdminStatCard label="Đã ẩn" value={String(query.data?.summary.hidden ?? 0)} icon={Trash2} tone="red" /></section><section className="overflow-hidden rounded-2xl border bg-white shadow-sm">{query.isLoading ? <AdminLoading /> : query.error || !query.data ? <AdminError /> : <><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50"><tr>{['Khách hàng', 'Provider', 'Đánh giá & phản hồi', 'Trạng thái', 'Thao tác'].map((h) => <th className="px-6 py-4" key={h}>{h}</th>)}</tr></thead><tbody>{query.data.items.map((item) => { const rating = item.servicesFeedbacks[0]; return <tr className="border-t" key={item._id}><td className="px-6 py-4 font-bold">{item.customerId?.fullName}</td><td className="px-6 py-4">{item.providerId?.userId?.fullName || '—'}</td><td className="px-6 py-4"><p className="font-bold text-amber-500">{rating?.rating ?? 0} ★</p><p className="max-w-md text-slate-600">{rating?.comment || 'Không có nội dung'}</p></td><td className="px-6 py-4"><AdminBadge tone={item.status === 'VISIBLE' ? 'green' : 'red'}>{item.status === 'VISIBLE' ? 'Hiển thị' : 'Đã ẩn'}</AdminBadge></td><td className="px-6 py-4"><button onClick={() => toggle.mutate({ id: item._id, status: item.status === 'VISIBLE' ? 'HIDDEN' : 'VISIBLE' })} className="rounded-lg p-2 text-slate-500">{item.status === 'VISIBLE' ? <EyeOff size={18} /> : <Eye size={18} />}</button></td></tr> })}</tbody></table></div><AdminPagination {...query.data} onPageChange={setPage} /></>}</section></div>
}
