import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Check, X } from 'lucide-react'
import { useState } from 'react'
import { adminService } from '../services/adminService'
import { AdminBadge, AdminError, AdminLoading, AdminPageHeader } from '../components/AdminUi'
export function AdminWithdrawalsPage() {
  const [status, setStatus] = useState('PENDING'); const client = useQueryClient()
  const query = useQuery({ queryKey: ['admin', 'withdrawals', status], queryFn: () => adminService.getWithdrawals(status) })
  const refresh = () => client.invalidateQueries({ queryKey: ['admin', 'withdrawals'] })
  const approve = useMutation({ mutationFn: adminService.approveWithdrawal, onSuccess: refresh })
  const reject = useMutation({ mutationFn: (id: string) => adminService.rejectWithdrawal(id, window.prompt('Lý do từ chối') || 'Thông tin chưa hợp lệ'), onSuccess: refresh })
  return <div className="space-y-6 p-4 sm:p-6 lg:p-8"><AdminPageHeader title="Phê duyệt rút tiền" description="Xác minh thông tin ngân hàng trước khi giải ngân." /><div className="flex gap-2">{[['PENDING', 'Chờ duyệt'], ['APPROVED', 'Đã duyệt'], ['REJECTED', 'Đã từ chối']].map(([v, l]) => <button key={v} onClick={() => setStatus(v)} className={`rounded-xl px-4 py-2 text-sm font-bold ${status === v ? 'bg-blue-600 text-white' : 'bg-white'}`}>{l}</button>)}</div><section className="overflow-hidden rounded-2xl border bg-white shadow-sm">{query.isLoading ? <AdminLoading /> : query.error || !query.data ? <AdminError /> : <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-50"><tr>{['Provider', 'Số tiền', 'Ngân hàng', 'Chủ tài khoản', 'Ngày tạo', 'Thao tác'].map((h) => <th className="px-6 py-4" key={h}>{h}</th>)}</tr></thead><tbody>{query.data.map((item) => <tr className="border-t" key={item._id}><td className="px-6 py-4 font-bold">{item.userId?.fullName}<p className="text-xs font-normal text-slate-500">{item.userId?.email}</p></td><td className="px-6 py-4 font-extrabold">{item.amount.toLocaleString('vi-VN')} ₫</td><td className="px-6 py-4">{item.bankName} · {item.accountNumber}</td><td className="px-6 py-4">{item.accountHolder}</td><td className="px-6 py-4">{new Date(item.createdAt).toLocaleDateString('vi-VN')}</td><td className="px-6 py-4">{item.status === 'PENDING' ? <div className="flex gap-2"><button onClick={() => approve.mutate(item._id)} className="rounded-lg bg-green-50 p-2 text-green-700"><Check size={18} /></button><button onClick={() => reject.mutate(item._id)} className="rounded-lg bg-red-50 p-2 text-red-700"><X size={18} /></button></div> : <AdminBadge tone={item.status === 'APPROVED' ? 'green' : 'red'}>{item.status}</AdminBadge>}</td></tr>)}</tbody></table></div>}</section></div>
}
