import { useNavigate } from 'react-router-dom'
import { GuestPageLayout } from '../components/GuestPageLayout'

const hero = 'https://lh3.googleusercontent.com/aida-public/AB6AXuDdFqBSgRAkwBNsmPEX3p9r4RIHuq2o71d5K-l3AKerjZoRJtzDFWwu5RojhIPlYaKda7NJ-mZ-cum5A8Q-5ug-pfUWSPuC0ZZKVtG2uVhSm1_lVIRElNxqEo-3F6rIHjgB0VD6hzoBo2MEpqKui3402XUpsy4UWi9BaQxnUQt0odLJ8MKYZJ_vV_y6j0V_qfsVhWhO9ALe8IvCSUQOjYgKGeBp-k3rwuPatfIz8Y3U2bb0EuBPtjX9YtLYaehfKbby2Sz7kaEJy_k'
const experts = [
  ['Trần Minh Quân', 'Kỹ thuật Điện', 'Chuyên gia giàu kinh nghiệm thực tế', 'https://lh3.googleusercontent.com/aida-public/AB6AXuCY6tmTj2kTlr23pbD-leOAVefT7aONYXZxhA08LEEm565phQNJmomRbRHJjqTiHDekXT2T67ZJWIo__wRysxbEUWOFcDL8YQOmcdJCezfnYkt4ixmRWwDGGHEHx5NXfminPiR3oKg_ToPaiEJ9BGmcr6FMZ5YPLu1u9iGSFZFUsceNns4_Z9wdW9bjo7ZdqxvZF5PzPnTBDQb6JqyRs5Uq2xiksc-HL0R2o-H_6plzV2GPrwumgUnABIIooDaKc7FAGR9Ermrnznk'],
  ['Lê Thanh Hương', 'Bảo trì Nội thất', 'Giám sát kỹ thuật khu vực', 'https://lh3.googleusercontent.com/aida-public/AB6AXuAlVjHOAHOPV2QnQ75qZTyTvikvG9HoX45nCH17aeCKbK8NEN_vrkPK_guby4hdlubSxoEgdboKLyc93vlUGmjVOhMFtI9d3Os4DJ7fFORxRAMhHCRfLj4ah8BUYeLwsH4VQol7EJgFyMuiWULW9LrwsDj6uZbxzxu1sVLa164sBVHgajcDTLzkl-ZXzJzwCSduN68w4jLt3jaY0KGE09vRCVLZl5M4haP5sFqeuLdyFeLNt6D8adenirRLBIVVDujcu5_xFAdJZYc'],
  ['Nguyễn Văn Đức', 'Hệ thống Nước', 'Chuyên gia xử lý sự cố cấp thoát nước', 'https://lh3.googleusercontent.com/aida-public/AB6AXuCyEZNatNYDn8fl6P8k4LB_k0DRG09dnGKHTpbbGwT9TFYQNtNf2mYF7ugu6Bzw693f8-a7qVNLgmGiNARxrOLcp0gCaayONgbnbzTGIkazXl_1abJJeXbGKLkxsj62dsBLy6ret5XmKghlor6rxxYSoQ2MLqs3FiW-qFQumG5kysMDJWjTUzy2R3uTKsev_l3FpU0ZZcwuDMVHVzJD7WeDsLO_P37PA9PswhqgI-KBzJXk1NrVi6Qact03t6QNz136vfTdqMB3MPM'],
  ['Phạm Hoàng Nam', 'Smart Home', 'Kỹ sư giải pháp thông minh', 'https://lh3.googleusercontent.com/aida-public/AB6AXuAE47tDdF5Mp_L9wXgnLvG6hAqLESyXiTJsNCtP6mUob1qd0aEcm6ZwCbOWbUOe69HlhtvRrxF0OP2ETA7kW9Miu4SxtEAchJXYaUIhlO17JM6eZiF-huxQRwYx-uQ2-EELYpZE9V7elrpyKoztgg-tVlGbmiPmn6wqYTFg9r295gZ7Jfz4belnM-gWywGNIaMNmoGYp_TCndCDVWn90rR5WzSU5U_d3J-6Or5VRdWvRwy7KSZBEQLXP0-lz0rBc19x8SzzL5uUNZs'],
]

export function GuestAboutPage() {
  const navigate = useNavigate()
  const book = () => navigate('/auth/login', { state: { redirectTo: '/customer/request/new' } })
  return (
    <GuestPageLayout>
      <section className="relative flex h-[550px] items-center justify-center overflow-hidden">
        <div className="absolute inset-0 bg-cover bg-center opacity-40" style={{ backgroundImage: `url('${hero}')` }} /><div className="absolute inset-0 bg-gradient-to-t from-background via-transparent to-transparent" />
        <div className="relative z-10 px-lg text-center"><h1 className="mb-md text-display-lg font-bold text-primary">Nâng tầm chất lượng<br />cuộc sống gia đình</h1><p className="mx-auto max-w-2xl text-body-lg text-on-surface-variant">FIXNOW không chỉ sửa chữa thiết bị, chúng tôi chăm sóc không gian sống của bạn bằng sự tận tâm và chuyên nghiệp cao nhất.</p></div>
      </section>
      <section className="mx-auto grid max-w-container-max gap-lg px-lg py-xxl md:grid-cols-12">
        <div className="rounded-xl border border-outline-variant bg-surface-container-low p-xl md:col-span-7"><span className="mb-base block text-label-sm uppercase tracking-widest text-primary">Sứ mệnh của chúng tôi</span><h2 className="mb-md text-headline-lg font-bold">Mang đến sự an tâm tuyệt đối cho mọi gia đình.</h2><p className="text-on-surface-variant">Chúng tôi cam kết cung cấp giải pháp bảo trì và sửa chữa nhà cửa minh bạch, nhanh chóng và chất lượng. FIXNOW là cầu nối tin cậy giữa những chuyên gia lành nghề nhất và những ngôi nhà đang cần sự chăm sóc.</p></div>
        <div className="rounded-xl border border-primary bg-primary-container p-xl text-on-primary-container md:col-span-5"><span className="mb-base block text-label-sm uppercase tracking-widest opacity-80">Tầm nhìn</span><h2 className="mb-xl text-headline-md font-semibold">Xây dựng hệ sinh thái dịch vụ gia đình thuận tiện và đáng tin cậy.</h2><div className="flex items-center gap-sm"><span className="material-symbols-outlined text-[48px]">auto_awesome</span><p className="text-label-md">Đổi mới công nghệ - Nâng cao tiêu chuẩn dịch vụ.</p></div></div>
      </section>
      <section className="mx-auto max-w-container-max px-lg py-xxl"><div className="mb-xl"><h2 className="text-headline-lg font-bold">Đội ngũ chuyên gia</h2><p className="mt-sm max-w-2xl text-on-surface-variant">Các kỹ thuật viên được đánh giá thông tin và chuyên môn trước khi cung cấp dịch vụ trên hệ thống.</p></div><div className="grid gap-lg sm:grid-cols-2 lg:grid-cols-4">{experts.map(([name, role, description, image]) => <article className="group" key={name}><div className="relative mb-md aspect-[3/4] overflow-hidden rounded-xl border border-outline-variant"><img className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-110" src={image} alt={name} /><span className="absolute right-0 bottom-0 left-0 bg-gradient-to-t from-black/60 p-md text-label-sm text-white">{role}</span></div><h3 className="text-title-lg font-semibold">{name}</h3><p className="text-on-surface-variant">{description}</p></article>)}</div></section>
      <section className="mx-auto max-w-container-max px-lg pb-xxl"><div className="rounded-[2rem] bg-surface-container-high p-xxl text-center"><h2 className="mb-md text-headline-lg font-bold">Bạn cần hỗ trợ ngay bây giờ?</h2><p className="mx-auto mb-xl max-w-xl text-body-lg text-on-surface-variant">Hãy để các chuyên gia FIXNOW hỗ trợ xử lý vấn đề trong ngôi nhà của bạn nhanh chóng và thuận tiện.</p><div className="flex flex-col justify-center gap-md sm:flex-row"><button className="rounded-full bg-primary px-xl py-md text-white" onClick={book}>Đặt dịch vụ ngay</button><button className="rounded-full border border-primary px-xl py-md text-primary" onClick={() => navigate('/support')}>Liên hệ tư vấn</button></div></div></section>
    </GuestPageLayout>
  )
}
