import { GuestPageLayout } from '../components/GuestPageLayout'

const hero = 'https://lh3.googleusercontent.com/aida-public/AB6AXuCuPIL__e4XQJtTmMaSNw8rv__s9NFwmrNJ5XX4LyakswZNAqcA8y5m9PlsbXOyjoEsgphBiYmE_HRWFAyZ73En07sEkvcwh_92ZTYd4h5qDoiaHG-5VCZRYUFSvqsIwRz4039q_aHoA6V16TS_enFTTg0_lzrfkTzClLxGdxjl2A8yWSmUjyvj6oA_ve3znSTc8iJHlVdpD-kFFD0HkDH_FKCQznbK3pIWk7qNglslK2UCBeH6ldLUlpOtCogm3iOz_1dWaHd_jjM'
const posts = [
  ['Điện gia dụng', 'Giải pháp tiết kiệm điện năng cho mùa cao điểm', 'Mùa nóng đang đến gần, hãy cùng điểm qua những thói quen và thiết bị giúp cắt giảm chi phí điện hàng tháng.', 'https://lh3.googleusercontent.com/aida-public/AB6AXuCJxmmJGxKYf85DufoXWB7iDObHZdP35w8YtVodSJmu2nBpajTQUsrvAKfiIR081rwE8JNXOQwZR8trmqOIg_hZHg88Zqos1YPFa6NQOnGKYHrgaAKdcda62hn16o1DVkrYRRwZ_hWUszsIR-h3aizNeOUqlp1Wu_RTpk9S6DxJmnK6yd8Ei4qnIReVIMrhntxcAoeR_3I5sb2QxZRGb4NVnppyb08frWLu9Z5LFyqLYaPv2uCBrnMkwOUMQ1UHfWJ0fUkrrVLOr-E'],
  ['An ninh', 'Bảo vệ ngôi nhà từ xa với hệ thống camera AI mới nhất', 'Công nghệ AI đã thay đổi hoàn toàn cách chúng ta giám sát và bảo vệ không gian sống.', 'https://lh3.googleusercontent.com/aida-public/AB6AXuAsbyzc0wVuVQIgO3ej83yJJlhxz0zVlbJuZZQ4BMOPViYcdQncmwan2kuIQITAXcjqGIAW5Sg-v6MKXU5l-_91jLUGS0oP4TD1CooMvoatEmLNx1U9xE3qpQRhS51jng8cMhWElwPx5qjkOCYOesJuBNFOYVWk15QAHCWnGegvWvE2vT-Db2G-nh0I39rbmguRVFgUc3Gnv5l4T7b5hLvWrdNAE7NneKXSctt1BfrMeNzY74xhU6juuIFodkifDd-XwYLVOLmE7TI'],
]

export function GuestBlogPage() {
  return (
    <GuestPageLayout>
      <section className="relative flex h-[400px] items-center overflow-hidden"><div className="absolute inset-0 bg-cover bg-center brightness-50" style={{ backgroundImage: `url('${hero}')` }} /><div className="relative z-10 mx-auto w-full max-w-container-max px-lg text-white"><span className="mb-md inline-block rounded-full bg-secondary-container px-md py-xs text-label-sm uppercase">Cẩm nang gia đình</span><h1 className="mb-md text-display-lg font-bold leading-tight">Mẹo Hay Mỗi Ngày Cho Ngôi Nhà Tiện Nghi</h1><p className="w-full text-body-lg text-surface-variant">Khám phá kinh nghiệm sửa chữa, xu hướng smarthome và bí quyết bảo trì từ các chuyên gia FixNow.</p></div></section>
      <section className="mx-auto w-full max-w-container-max px-lg py-xl"><div className="flex flex-wrap gap-md">{['Tất cả bài viết', 'Sửa chữa điện nước', 'Mẹo vặt gia đình', 'Smarthome', 'Thi công nội thất'].map((category, index) => <button className={`rounded-xl px-lg py-sm text-label-md ${index === 0 ? 'bg-primary text-white' : 'bg-surface-container-high text-on-surface-variant'}`} key={category}>{category}</button>)}</div></section>
      <section className="mx-auto grid w-full max-w-container-max gap-lg px-lg pb-xxl md:grid-cols-12">
        <article className="group min-w-0 md:col-span-8"><div className="relative mb-md aspect-video overflow-hidden rounded-2xl border border-outline-variant"><div className="h-full w-full bg-cover bg-center transition-transform duration-500 group-hover:scale-105" style={{ backgroundImage: "url('https://lh3.googleusercontent.com/aida-public/AB6AXuAISP5mtAIM48fGrFNgQl4Q0ms4PZiLgFgHXgsGKety4_cZSe-nsrIrD07t-C1rtWW-_3CUeeX88XEHoov2IghF6NGkfoy3rR5-zsN-lrXE_8oeamZVtOr9C2wYyKWFvlj4r536tIguVBoZVL5vNrzAzKiz5gIkhbmw_1osb1-1ECtVKlyB8_CgV74fOOkEmEOxuE0x2HFYKdDkwOQbBfjxV87ORq8QHSeTWuUtVH5YgSIsmzkDQD52ywsXa0HWxXripab1Po3ULdM')" }} /><span className="absolute top-md left-md rounded-lg bg-primary px-md py-xs text-label-sm text-white">Nổi bật</span></div><p className="mb-xs text-label-sm text-on-surface-variant">20 Tháng 10, 2024 · 8 phút đọc</p><h2 className="mb-sm text-headline-lg leading-tight font-bold transition-colors group-hover:text-primary">7 Bước Thiết Lập Hệ Thống Smarthome Tối Ưu Cho Căn Hộ Chung Cư</h2><p className="w-full text-on-surface-variant">Làm thế nào để biến căn hộ trở nên thông minh hơn mà không tốn quá nhiều chi phí?</p></article>
        <div className="flex flex-col gap-lg md:col-span-4">{[['Kinh nghiệm', 'Bộ dụng cụ sửa chữa cơ bản mọi nhà đều nên có', 'https://lh3.googleusercontent.com/aida-public/AB6AXuDPVkdvyZkaB8BlIHgHb3wLseKQ1TIw3LDi4uPMxkg0qsQjzbHz_EBNgyaPtXEs_JaPzG_wgXWFuWmWtQaZTJwCxePh28vob1qNAVWQHCORwsm9q2GCk57LaFx7A-ovp6yM44FACuCbGp1Q3_0JmMezov9fS5AsG-uEF6SJdka2DXkvJyf1obGosNZ50OlAf624W-VvdEBcjKkyRRt5oQGlO_jJOjNEj0RzPII3kmSTidpgPGR_F9lTC8MH75RoWetINm7Z574FHvU'], ['Mẹo vặt', 'Cách khắc phục vòi nước rò rỉ trong 15 phút', 'https://lh3.googleusercontent.com/aida-public/AB6AXuCqVzyWn8872yLLjxSOvc2aNWVOQ-aC1T7sNpE4haTjH3xDH2BuVulPf4KhbXXHcv1CG9Y7pWK6l8--BGEypGH-_epmy4RdUeEtUhlQeXH86wv0NemvmSrYHNfmvu6vfVAprvc9TEn0zUVu771-B7tGMX9TQATPI7dy3akKl6VnwGhMu9cRkReG_PtQ8R7arsAkIQCkywAuLGC7gKuow2SA3-jC9BTyUmQ-_hDvSPX4TXfbd7F2LEXjcnooc9Ii-RYSjZvIgtzupJ4']].map(([category, title, image]) => <article className="group" key={title}><div className="mb-sm aspect-video overflow-hidden rounded-xl border border-outline-variant"><img className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105" src={image} alt={title} /></div><span className="mb-xs block text-label-sm font-bold text-tertiary">{category}</span><h3 className="text-title-lg font-semibold group-hover:text-primary">{title}</h3></article>)}</div>
      </section>
      <section className="mx-auto w-full max-w-container-max px-lg pb-xxl"><h2 className="mb-xl text-headline-md font-semibold">Bài viết gần đây</h2><div className="space-y-xl">{posts.map(([category, title, description, image]) => <article className="group grid grid-cols-1 gap-lg border-b border-outline-variant pb-xl md:grid-cols-[minmax(260px,1fr)_2fr]" key={title}><img className="aspect-[4/3] h-full w-full rounded-xl object-cover" src={image} alt={title} /><div className="min-w-0"><span className="mb-sm inline-block rounded-full bg-surface-container-highest px-md py-xs text-label-sm">{category}</span><h3 className="mb-md text-headline-md leading-snug font-semibold group-hover:text-primary">{title}</h3><p className="w-full text-on-surface-variant">{description}</p></div></article>)}</div></section>
    </GuestPageLayout>
  )
}
